### ISSUE TITLE
Serialize/ Deserialize XMP

### ISSUE THREAD

**Issue by edispring** [Lambda-IT/xmp-toolkit#2]
https://en.wikipedia.org/wiki/JSON-LD
http://json-ld.org/playground/

-->https://github.com/digitalbazaar/jsonld.js

Ev RDF zu JSON-LD konvertieren?

xmp deserialize saxparser?
https://github.com/isaacs/sax-js

**Comment by marcberchtold** [comment]
Is implemented in a separate project
